server:
  port: 8181
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: myappclient
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myapprealm
            user-name-attribute: mike
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myapprealm
          jwk-set-uri: http://localhost:8080/realms/newmyapprealm/protocol/openid-connect/serts
  application:
    name: spring_security
  datasource:
    url: jdbc:postgresql://147.45.151.57:5432/mkustov
    username: mkustov
    password: mkustov1
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.yml